version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"

  memcached:
    image: memcached:alpine
    expose:
      - "11211"

  processor:
    build: ./processor
    ports:
      - "5001:5001"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
