version: "3.8"
services:
  frontend:
    image: jonhels/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: jonhels/backend:latest
    ports:
      - "4000:4000"

  nginx:
    image: jonhels/nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend

  redis:
    image: jonhels/redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
