version: "3.8"
services:
  frontend:
    image: jonhels/frontend:latest
    ports:
      - "3000:3000"

  backend:
    image: jonhels/backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  nginx:
    image: jonhels/nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend

  memcached:
    image: memcached:alpine
    expose:
      - "11211"

  processor:
    image: jonhels/processor:latest
    ports:
      - "5001:5001"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
