name: Continuous Like Batcher

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs the script every 5 minutes

jobs:
  run_like_batcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run like_batcher.py
        run: python like_batcher.py
